services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres.hsyobnhphvokmseogebq
      SPRING_DATASOURCE_PASSWORD: golfART212@@

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"